version: '3.7'

services:
  nodejs:
    image: node:12.16.1
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: bash -c "npm install && npm run dev"