FROM php:7.4.9-apache

RUN pecl install -f xdebug \
&& echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini;

WORKDIR /var/www/html
RUN apt-get update && apt-get install -y mariadb-client && apt-get install -y sendmail libpng-dev libsodium23 unzip git libjpeg-dev libxpm-dev libfreetype6-dev libjpeg62-turbo-dev libgd-dev \
    && docker-php-ext-configure gd \
    --with-jpeg=/usr/include/ \
    --with-freetype=/usr/include/

RUN docker-php-ext-install mysqli gd pdo pdo_mysql exif
RUN docker-php-ext-enable mysqli

RUN apt-get install -y \
        libzip-dev \
        zip \
  && docker-php-ext-install zip

#RUN apt-get update && \
#    apt-get install -y \
#        zlib1g-dev

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer

#mientras# RUN docker-php-ext-install mbstring
#RUN docker-php-ext-install zip
#mientras# RUN docker-php-ext-install gd


RUN touch /usr/local/etc/php/conf.d/uploads.ini \
    && echo "post_max_size = 6G;" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "upload_max_filesize = 4G;" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "memory_limit = 8G;" >> /usr/local/etc/php/conf.d/uploads.ini \
    && echo "max_execution_time = 1800;" >> /usr/local/etc/php/conf.d/uploads.ini  
    
RUN apt-get install net-tools
RUN echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20170718/xdebug.so" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_autostart=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_log=/var/www/html/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini \
    && echo "xdebug.remote_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

RUN docker-php-ext-enable xdebug

RUN apt-get install libxrender1
RUN curl "https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-AMD64.tar.xz" -L -o "wkhtmltopdf.tar.xz"
RUN tar Jxvf wkhtmltopdf.tar.xz
RUN mv wkhtmltox/bin/wkhtmltopdf /usr/local/bin/wkhtmltopdf
#RUN apt-get install libssl1.0-dev

#RUN pecl install -o -f redis &&  rm -rf /tmp/pear &&  docker-php-ext-enable redis

RUN a2enmod rewrite
